apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: storage
  name: nfs-direct-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi